### ISSUE TITLE
Where is the VR nose.png?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Fubaxiusz/fubax-shaders-dev#1]
Your post

https://reshade.me/forum/shader-presentation/5104-vr-universal-shader

has a link to

https://github.com/Fubaxiusz/fubax-shaders-dev/blob/master/Textures/nose.png

But it's 404. I download repository zip, also not found nose.png.

**Comment by Fubaxiusz** [comment]
Thanks for pointing this out. I forgot to copy this texture when I moved unfinished shaders to new repository. Now the file is there.
